groups:

- name: all
  jobs:
  - init-env
  - deploy-iaas
  - config-opsman-auth
  - config-director
  - deploy-director
  - upload-ert
  - configure-ert
  - deploy-ert

- name: init
  jobs:
  - init-env

- name: iaas
  jobs:
  - deploy-iaas
  - config-opsman-auth
  - config-director
  - deploy-director

- name: ert
  jobs:
  - upload-ert
  - configure-ert
  - deploy-ert


resource_types:
- name: azure-blob
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: terraform-state
  type: azure-blob
  source:
    container: {{terraform_statefile_container}}
    storage_account_name: {{azure_account_name}}
    storage_access_key: {{azure_access_key}}
    regexp: terraform.tfstate

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{githubtoken}}

- name: pivnet-opsmgr
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pivnet-elastic-runtime
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
#####################
## Job - Init Env  ##
#####################
- name: init-env
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: false
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"

  - task: wipe-env
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
      outputs:
        - name: opsman-metadata
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/init/wipe-env.sh
      params:
        arg_wipe: {{arg_wipe}}
        azure_pcf_terraform_template: {{azure_pcf_terraform_template}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_tenant_id: {{azure_tenant_id}}
        azure_service_principal_id: {{azure_service_principal_id}}
        azure_service_principal_password: {{azure_service_principal_password}}
        azure_region: {{azure_region}}
        azure_terraform_prefix: {{azure_terraform_prefix}}

  - task: init-public-ips
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
      outputs:
        - name: opsman-metadata
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/init/init-public-ip.sh
      params:
        arg_wipe: {{arg_wipe}}
        azure_pcf_terraform_template: {{azure_pcf_terraform_template}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_tenant_id: {{azure_tenant_id}}
        azure_service_principal_id: {{azure_service_principal_id}}
        azure_service_principal_password: {{azure_service_principal_password}}
        azure_region: {{azure_region}}
        azure_terraform_prefix: {{azure_terraform_prefix}}
        azure_terraform_vnet_cidr: {{azure_terraform_vnet_cidr}}
        azure_terraform_subnet_infra_cidr: {{azure_terraform_subnet_infra_cidr}}
        azure_terraform_subnet_ert_cidr: {{azure_terraform_subnet_ert_cidr}}
        azure_terraform_subnet_services1_cidr: {{azure_terraform_subnet_services1_cidr}}
        azure_terraform_subnet_dynamic_services_cidr: {{azure_terraform_subnet_dynamic_services_cidr}}
        pcf_ert_domain: {{pcf_ert_domain}}



#######################
## Job - Deploy-Iaas ##
#######################
- name: deploy-iaas
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: false
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: pivnet-opsmgr
      trigger: false
      params:
        globs:
        - "*Azure.yml"

  - task: upload-opsman
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: pivnet-opsmgr
      outputs:
        - name: opsman-metadata
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/upload-opsman.sh

  - task: deploy-iaas
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: opsman-metadata
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/deploy-iaas.sh
      params:
        azure_pcf_terraform_template: {{azure_pcf_terraform_template}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_tenant_id: {{azure_tenant_id}}
        azure_service_principal_id: {{azure_service_principal_id}}
        azure_service_principal_password: {{azure_service_principal_password}}
        azure_region: {{azure_region}}
        azure_terraform_prefix: {{azure_terraform_prefix}}
        azure_vm_admin: {{azure_vm_admin}}
        azure_vm_password: {{azure_vm_password}}
        pcf_ert_domain: {{pcf_ert_domain}}
        pcf_opsman_admin: {{pcf_opsman_admin_username}}
        pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
        pcf_ssh_key_pub: {{pcf_ssh_key_pub}}
        azure_account_name: {{azure_account_name}}
        azure_buildpacks_container: {{azure_buildpacks_container}}
        azure_droplets_container: {{azure_droplets_container}}
        azure_packages_container: {{azure_packages_container}}
        azure_resources_container: {{azure_resources_container}}

##############################
## Job - Config OpsMan Auth ##
##############################
- name: config-opsman-auth
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [deploy-iaas]
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: config-opsman
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/config-opsman.sh
      params:
        pcf_ert_domain: {{pcf_ert_domain}}
        pcf_opsman_admin: {{pcf_opsman_admin_username}}
        pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}

###########################
## Job - Config-Director ##
###########################
- name: config-director
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [config-opsman-auth]
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: config-director
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/config-director.sh
      params:
        pcf_ert_domain: {{pcf_ert_domain}}
        pcf_opsman_admin: {{pcf_opsman_admin_username}}
        pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
        azure_pcf_terraform_template: {{azure_pcf_terraform_template}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_tenant_id: {{azure_tenant_id}}
        azure_service_principal_id: {{azure_service_principal_id}}
        azure_service_principal_password: {{azure_service_principal_password}}
        azure_terraform_prefix: {{azure_terraform_prefix}}
        azure_terraform_subnet_infra_cidr: {{azure_terraform_subnet_infra_cidr}}
        azure_terraform_subnet_infra_reserved: {{azure_terraform_subnet_infra_reserved}}
        azure_terraform_subnet_infra_dns: {{azure_terraform_subnet_infra_dns}}
        azure_terraform_subnet_infra_gateway: {{azure_terraform_subnet_infra_gateway}}
        azure_terraform_subnet_ert_cidr: {{azure_terraform_subnet_ert_cidr}}
        azure_terraform_subnet_ert_reserved: {{azure_terraform_subnet_ert_reserved}}
        azure_terraform_subnet_ert_dns: {{azure_terraform_subnet_ert_dns}}
        azure_terraform_subnet_ert_gateway: {{azure_terraform_subnet_ert_gateway}}
        azure_terraform_subnet_services1_cidr: {{azure_terraform_subnet_services1_cidr}}
        azure_terraform_subnet_services1_reserved: {{azure_terraform_subnet_services1_reserved}}
        azure_terraform_subnet_services1_dns: {{azure_terraform_subnet_services1_dns}}
        azure_terraform_subnet_services1_gateway: {{azure_terraform_subnet_services1_gateway}}
        azure_terraform_subnet_dynamic_services_cidr: {{azure_terraform_subnet_dynamic_services_cidr}}
        azure_terraform_subnet_dynamic_services_reserved: {{azure_terraform_subnet_dynamic_services_reserved}}
        azure_terraform_subnet_dynamic_services_dns: {{azure_terraform_subnet_dynamic_services_dns}}
        azure_terraform_subnet_dynamic_services_gateway: {{azure_terraform_subnet_dynamic_services_gateway}}
        pcf_ssh_key_pub: {{pcf_ssh_key_pub}}
        pcf_ssh_key_priv: {{pcf_ssh_key_priv}}

###########################
## Job - Deploy-Director ##
###########################
- name: deploy-director
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [config-director]
    - get: pivnet-opsmgr
      trigger: true
      params: {globs: []}
    - get: tool-om
      params:
        globs:
        - "om-linux"
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"

  - task: deploy-director
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/deploy-director.sh
      params:
        pcf_ert_domain: {{pcf_ert_domain}}
        pcf_opsman_admin: {{pcf_opsman_admin_username}}
        pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}

###########################
## Job - Upload ERT      ##
###########################
- name: upload-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [deploy-director]
      trigger: true
      params: {globs: []}
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      params:
        globs:
        - "*pivotal"

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{pcf_opsman_admin_username}}
      OPS_MGR_PWD: {{pcf_opsman_admin_password}}
      PIVNET_API_TOKEN: {{pcf_pivnet_token}}
      IAAS: "azure"
      NO_PROXY: ""
      OM_IP: ""

  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      PRODUCT_NAME: cf

###########################
## Job - Configure ERT   ##
###########################
- name: configure-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [upload-ert]
      trigger: true
    - get: terraform-state
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: configure-json
    file: pcf-pipelines/tasks/install-ert/configure-json/task.yml
    params:
      pcf_iaas: {{pcf_iaas}}
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
      pcf_ert_ssl_cert: {{pcf_ert_ssl_cert}}
      pcf_ert_ssl_key: {{pcf_ert_ssl_key}}
      terraform_template: {{azure_pcf_terraform_template}}
      terraform_prefix: {{azure_terraform_prefix}}
      pcf_ert_saml_cert: {{pcf_ert_saml_cert}}
      pcf_ert_saml_key: {{pcf_ert_saml_key}}
      pcf_ert_networking_pointofentry: {{pcf_ert_networking_pointofentry}}
      azure_access_key: {{azure_access_key}}
      azure_account_name: {{azure_account_name}}
      azure_buildpacks_container: {{azure_buildpacks_container}}
      azure_droplets_container: {{azure_droplets_container}}
      azure_packages_container: {{azure_packages_container}}
      azure_resources_container: {{azure_resources_container}}
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      pcf_az_1:
      pcf_az_2:
      pcf_az_3:
      gcp_storage_access_key: 
      gcp_storage_secret_key:
      db_diego_username: 
      db_diego_password:
      db_notifications_username:
      db_notifications_password:
      db_autoscale_username:
      db_autoscale_password:
      db_uaa_username:
      db_uaa_password:
      db_app_usage_service_username:
      db_app_usage_service_password:
      db_ccdb_username:
      db_ccdb_password:
      db_routing_username:
      db_routing_password:
      db_accountdb_username:
      db_accountdb_password:
      db_networkpolicyserverdb_username:
      db_networkpolicyserverdb_password:
      db_nfsvolumedb_username:
      db_nfsvolumedb_password:
      db_silk_username:
      db_silk_password:
      db_locket_username:
      db_locket_password:
      S3_ENDPOINT:

  - task: configure-ert
    file: pcf-pipelines/tasks/install-ert/configure-ert/task.yml
    params:
      pcf_iaas: {{pcf_iaas}}
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
      
###########################
## Job - Deploy    ERT   ##
###########################
- name: deploy-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]

  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [configure-ert]
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: deploy-ert
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
