# Whether to allow SSH access to application instances
allow_app_ssh_access: false

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
first_name_attribute:
group_search_base:
group_search_filter:
last_name_attribute:
ldap_pwd:
ldap_url:
ldap_user:
mail_attribute_name:
search_base:
search_filter:

# AZ configuration for Ops Director
az_1_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ1
az_1_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_1_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ1
az_2_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ2
az_2_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_2_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ2
az_3_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ3
az_3_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_3_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ3

# vSphere datastore folder (such as pcf_disk) where attached disk images will be created
bosh_disk_path: "pcf_disk"

# vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_template_folder: "pcf_templates"

# vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_vm_folder: "pcf_vms"

# Ciphers
# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
# The recommended settings are filled in below, change as necessary.
haproxy_tls_ciphers: "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
router_tls_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

# Company Name for Apps Manager
company_name:

# If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager
company_proxy_domain:

# c2c networking network cidr
container_networking_nw_cidr: 10.255.0.0/16

# For credhub integration, Set the number of credhub instances in resource config to 2
# Primary Encryption Name MUST match one of the encryption key names provided
# Encryption keys 2 and 3 are optional
# Note: The secret key needs to be 20 characters or more.
credhub_primary_encryption_name: dummy encryption key 1
credhub_encryption_key_name1: dummy encryption key 1
credhub_encryption_key_secret1: CHANGEME_CHANGEME_CHANGEME_CHANGEME
credhub_encryption_key_name2: # Optional Name 2
credhub_encryption_key_secret2: # Optional Secret 2
credhub_encryption_key_name3: # Optional Name 3
credhub_encryption_key_secret3: # Optional Secret 2

default_quota_max_number_services: 1000
default_quota_memory_limit_mb: 10240

# Deployment
deployment_excluded_range: CHANGEME    # Deployment network exclusion range
deployment_network_name: "DEPLOYMENT"
deployment_nw_azs: CHANGEME            # Comma separated list of AZ’s to be associated with this network
deployment_nw_cidr: CHANGEME           # Deployment network CIDR, ex: 10.0.0.0/22
deployment_nw_dns: CHANGEME            # Deployment network DNS
deployment_nw_gateway: CHANGEME        # Deployment network Gateway
deployment_vsphere_network: CHANGEME   # vCenter Deployment network name

## Domain names for deployment
apps_domain: CHANGEME   # e.g. apps.pcf.example.com
system_domain: CHANGEME # e.g. system.pcf.example.com

# Disable HTTP on gorouters (true|false)
disable_http_proxy: false

# If true, disable insecure cookies on the router.
disable_insecure_cookies: false

# Dynamic Services Network
dynamic_services_excluded_range: CHANGEME      # Dynamic Services network exclusion range
dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_nw_azs: CHANGEME              # Comma separated list of AZ’s to be associated with this network
dynamic_services_nw_cidr: CHANGEME             # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_nw_dns: CHANGEME              # Dynamic Services network DNS
dynamic_services_nw_gateway: CHANGEME          # Dynamic Services network Gateway
dynamic_services_vsphere_network: CHANGEME     # vCenter Dynamic Services network name

# Whether to enable BOSH VM resurrector
enable_vm_resurrector: true

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string - equivalent to none)
#   Any combination of the following, separated by comma:
#     bootstrap
#     deploy-autoscaler
#     deploy-notifications
#     deploy-notifications-ui
#     nfsbrokerpush
#     push-apps-manager
#     push-pivotal-account
#     push-usage-service
#     rejoin-unsafe
#     send-email
#     smoke_tests
#     test-autoscaling
ert_errands_to_disable: none

# PCF Elastic Runtime minor version to track
ert_major_minor_version: ^2\.1\.[0-9]+$ # ERT minor version to track (e.g ^2\.1\.[0-9]+$ will track 2.0.x versions)

# AZ to use for deployment of ERT Singleton jobs
ert_singleton_job_az: CHANGEME

# Optional. Duration in seconds to maintain an open connection when client supports keep-alive.
frontend_idle_timeout:



# Optional - if your git repo requires an SSH key.
git_private_key:

# Required if haproxy_forward_tls is enabled - HAProxy will use the CA provided to verify the certificates provided by the router.
haproxy_backend_ca:

# If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_forward_tls: enable

# Network configuration for Ops Director
icmp_checks_enabled: true     # Enable or disable ICMP checks

# Whether to disable SSL cert verification for this environment
ignore_ssl_cert_verification: false

# Infrastructure Configuration
infra_excluded_range: CHANGEME         # Infrastructure network exclusion range
infra_network_name: "INFRASTRUCTURE"
infra_nw_azs: CHANGEME                 # Comma separated list of AZ’s to be associated with this network
infra_nw_cidr: CHANGEME                # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_nw_dns: CHANGEME                 # Infrastructure network DNS
infra_nw_gateway: CHANGEME             # Infrastructure network Gateway
infra_vsphere_network: CHANGEME        # vCenter Infrastructure network name

# IPs
ha_proxy_ips:           # Comma-separated list of static IPs
router_static_ips:      # Comma-separated list of static IPs
ssh_static_ips:         # Comma-separated list of static IPs
tcp_router_static_ips:  # Comma-separated list of static IPs

# Instances
## Default resource configuration
## these resources can take any parameter made available in
## the ops manager API ( https://<your-ops-man/docs#configuring-resources-for-a-job )
backup_prepare_instances: 0
clock_global_instances: 1
cloud_controller_instances: 2
cloud_controller_worker_instances: 2
credhub_instances: 0
diego_brain_instances: 3
diego_cell_instances: 3
diego_database_instances: 3
doppler_instances: 3
ha_proxy_instances: 0
loggregator_trafficcontroller_instances: 1
mysql_instances: 3
mysql_monitor_instances: 1
mysql_proxy_instances: 2
nats_instances: 2
nfs_server_instances: 1
router_instances: 3
syslog_adapter_instances: 3
syslog_scheduler_instances: 2
tcp_router_instances: 0
uaa_instances: 2

# Whether or not the ERT VMs are internet connected.
internet_connected: true

# Loggegrator Port. Default is 443
loggregator_endpoint_port:

# Max threads count for deploying VMs
max_threads: 30

# Email address to receive MySQL monitor notifications
mysql_monitor_email:

#nsx configuration
nsx_address:                      # address of nsx
nsx_ca_certificate:               # cert for nsx
nsx_networking_enabled: false     # (true|false) to use nsx networking feature
nsx_password:                     # password for nsx access
nsx_username:                     # username for nsx access

# nsx fields
# leave nsx fields empty if you are not leveraging the nsx features for a given component
diego_brain_nsx_lb_edge_name:
diego_brain_nsx_lb_pool_name:
diego_brain_nsx_lb_port:
diego_brain_nsx_lb_security_group:
diego_brain_nsx_security_group:
mysql_nsx_lb_edge_name:
mysql_nsx_lb_pool_name:
mysql_nsx_lb_port:
mysql_nsx_lb_security_group:
mysql_nsx_security_group:
router_nsx_lb_edge_name:
router_nsx_lb_pool_name:
router_nsx_lb_port:
router_nsx_lb_security_group:
router_nsx_security_group:
tcp_router_nsx_lb_edge_name:
tcp_router_nsx_lb_pool_name:
tcp_router_nsx_lb_port:
tcp_router_nsx_lb_security_group:
tcp_router_nsx_security_group:

# Comma-separated list of NTP servers to use for VMs deployed by BOSH
ntp_servers: CHANGEME

# Decryption password for Ops Manager exported settings
om_decryption_pwd: CHANGEME

# Comma separated list of DNS servers used by Ops Manager
om_dns_servers: CHANGEME

# Gateway for Ops Manager network
om_gateway: CHANGEME

# IP to assign to Ops Manager VM
om_ip: CHANGEME

# Netmask for Ops Manager network
om_netmask: CHANGEME

# Comma-separated list of NTP Servers
om_ntp_servers: CHANGEME

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool: CHANGEME

# Optional - vCenter folder to put Ops Manager in
# Format: /<Data Center Name>/vm/<folder_name>
om_vm_folder:

# Optional - vCenter host to deploy Ops Manager in
om_vm_host:

# Name to use for Ops Manager VM
om_vm_name: CHANGEME

# vCenter network name to use to deploy Ops Manager in
om_vm_network: CHANGEME

# Whether to power on Ops Manager VM after creation
om_vm_power_state: true

# Optional DNS name for Ops Director. Should be reachable from all networks.
ops_dir_hostname:

# opsman_admin_username/opsman_admin_password needs to be specified
opsman_admin_username: CHANGEME       # Username for Ops Manager admin account
opsman_admin_password: CHANGEME       # Password for Ops Manager admin account

# Disk type for Ops Manager VM (thick|thin)
opsman_disk_type: "thin"

# FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com
opsman_domain_or_ip_address: CHANGEME

# PCF Ops Manager minor version to track
opsman_major_minor_version: ^2\.1\.[0-9]+$ # Ops Manager minor version to track (e.g ^2\.1\.[0-9]+$ will track 2.0.x versions)

# SSH password for Ops Manager (ssh user is ubuntu)
opsman_ssh_password: CHANGEME

# Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: CHANGEME

# Optional. If blank the cert(s) will be generated
poe_ssl_name1:
poe_ssl_cert1:
poe_ssl_key1:

poe_ssl_name2:
poe_ssl_cert2:
poe_ssl_key2:

poe_ssl_name3:
poe_ssl_cert3:
poe_ssl_key3:

# Request timeout for gorouter
router_request_timeout_in_seconds: 900

# Enable/disable route services (enable|disable)
route_services: disable

# Optional - these certificates can be used to validate the certificates from incoming client requests.
# All CA certificates should be appended together into a single collection of PEM-encoded entries.
routing_custom_ca_certificates:

# Support for the X-Forwarded-Client-Cert header. Possible values: (load_balancer|ha_proxy|router)
routing_tls_termination:

## Wildcard domain certs go here
# Optional. Will be generated if blank.
saml_ssl_cert:
saml_ssl_private_key:

# Setting appropriate Application Security Groups is critical for a secure
# deployment. Change the value of the param below to "X" to acknowledge that
# once the Elastic Runtime deployment completes, you will review and set the
# appropriate application security groups.
# See https://docs.pivotal.io/pivotalcf/opsguide/app-sec-groups.html
security_acknowledgement: CHANGEME

# Services network
services_excluded_range: CHANGEME      # Services network exclusion range
services_network_name: "SERVICES"
services_nw_azs: CHANGEME              # Comma separated list of AZ’s to be associated with this network
services_nw_cidr: CHANGEME             # Services network CIDR, ex: 10.0.0.0/22
services_nw_dns: CHANGEME              # Services network DNS
services_nw_gateway: CHANGEME          # Services network Gateway
services_vsphere_network: CHANGEME     # vCenter Services network name

# If true, disable SSL certificate verification for this environment.
skip_cert_verify: false

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd,
# smtp_enable_starttls_auto, and smtp_auth_mechanism must also be set.
smtp_address:
smtp_auth_mechanism: # (none|plain|cram-md5)
smtp_enable_starttls_auto: true
smtp_from:
smtp_port:
smtp_pwd:
smtp_user:

# Storage
ephemeral_storage_names: CHANGEME  # Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: CHANGEME # Persistent Storage names in vCenter for use by PCF

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
enable_security_event_logging: false
syslog_drain_buffer_size: 10000
syslog_host:
syslog_port:
syslog_protocol:

# Enable/disable TCP routing (enable|disable)
tcp_routing: disable

# A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478
tcp_routing_ports:

# Optional PEM-encoded certificates to add to BOSH director
trusted_certificates:         # Trusted certificates to be deployed along with all VM’s provisioned by BOSH

# vCenter configuration
vcenter_ca_cert: CHANGEME          # vCenter CA cert at the API endpoint; enter a value if `vcenter_insecure: 0`
vcenter_datacenter: CHANGEME       # vCenter datacenter
vcenter_datastore: CHANGEME        # vCenter datastore name to deploy Ops Manager in
vcenter_host: CHANGEME             # vCenter host or IP
vcenter_insecure: CHANGEME         # vCenter skip TLS cert validation; enter `1` to disable cert verification, `0` to enable verification
vcenter_pwd: CHANGEME              # vCenter password
vcenter_usr: CHANGEME              # vCenter username. If user is tied to a domain, then escape the \, example `domain\\user`

# Disk type for BOSH provisioned VM. (thick|thin)
vm_disk_type: "thick"
