#!/bin/bash

rm -fR _builds _steps _projects
isinit=$1
local="--docker-local"
echo $isinit
if [[ "$isinit" == "init" ]]; then
    echo "pulling latest docker containers"
    local=""
fi
wercker --verbose --environment ".testrunner_env_defaults" build --git-domain github.com --git-owner c0-ops --git-repository concourse-tasks-bundle ${local}
rm -fR _builds _steps _projects .wercker _cache _temp
