# The following should be set to a unique prefix. It will be used to prefix all
# the terraform resources created by the pipeline
os_resource_prefix: #CHANGEME

# The S3 access credentials for storing terraform state.
s3_endpoint:
s3_output_bucket:
tf_aws_access_key:
tf_aws_secret_key:

# The network names should start with the prefix above.
infra_network: #CHANGEME               # e.g {prefix}-infra-net
ert_network: #CHANGEME                 # e.g {prefix}-ert-net
services_network: #CHANGEME            # e.g {prefix}-services-net
dynamic_services_network: #CHANGEME    # e.g {prefix}-dynamic-services-net

infra_subnet_cidr: 10.1.0.0/24
infra_gateway: 10.1.0.1
infra_reserved_ip_ranges: 10.1.0.0-10.1.0.9
ert_subnet_cidr: 10.2.0.0/24
ert_gateway: 10.2.0.1
ert_reserved_ip_ranges: 10.2.0.0-10.2.0.9
services_subnet_cidr: 10.3.0.0/24
services_gateway: 10.3.0.1
services_reserved_ip_ranges: 10.3.0.0-10.3.0.9
dynamic_services_subnet_cidr: 10.4.0.0/24
dynamic_services_gateway: 10.4.0.1
dynamic_services_reserved_ip_ranges: 10.4.0.0-10.4.0.9

# TODO: Allow multiple DNS servers for each net (currently only 1 can be set)
infra_dns: #CHANGEME
ert_dns: #CHANGEME
services_dns: #CHANGEME
dynamic_services_dns: #CHANGEME
external_network_id: #CHANGEME      # Set this to your floating IP network's id
external_network: #CHANGEME         # Set this to your floating IP network
infra_nw_azs: #CHANGEME             # Comma-separated list of AZs
ert_nw_azs: #CHANGEME               # Comma-separated list of AZs
services_nw_azs: #CHANGEME          # Comma-separated list of AZs
dynamic_services_nw_azs: #CHANGEME  # Comma-separated list of AZs

security_group: pcf-secgroup   # Name of security group to create/use

# These are simply the project users credentials, downloaded from Horizon.
# The pre_os_cacert is the root CA cert, only needed if the openstack API's
# are fronted by a self-signed SSL certificate.
os_auth_url: #CHANGEME
os_identity_api_version: #CHANGEME
os_username: #CHANGEME
os_password: #CHANGEME
os_user_domain_name: #CHANGEME
os_project_name: #CHANGEME
os_project_id: #CHANGEME
os_tenant: #CHANGEME
os_region_name: #CHANGEME
os_interface: public
os_networking_model: #CHANGEME (nova|neutron)
pre_os_cacert: # Set if needed (see above)

opsman_public_key: #CHANGEME # The public key of your opsman key

opsman_volume_size: 100  # OpsMan VM disk size in GB

# AZ configuration for Ops Director
az_01_name: #CHANGEME
#az_02_name: #CHANGEME
#az_03_name: #CHANGEME
ert_singleton_job_az: #CHANGEME # AZ to use for deployment of ERT Singleton jobs

# Resource configuration
pivnet_token: #CHANGEME               # Pivotal Network token
opsman_major_minor_version: 1\.12\.* # Minor version of Ops Mgr to track
ert_major_minor_version: 1\.12\.*    # Minor version of Elastic Runtime to track

# Ops Manager VM Settings
opsman_image: ops-manager        # Prefix for the ops man glance image
opsman_flavor: m1.xlarge         # Ops man VM flavor
opsman_domain_or_ip_address: #CHANGEME            # FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com
opsman_admin_username: admin     # Username for Ops Manager admin account
opsman_admin_password: #CHANGEME # Password for Ops Manager admin account
om_decryption_pwd: #CHANGEME     # Decryption password for Ops Manager exported settings

# IaaS configuration for Ops Director
ignore_server_az: false # If true, set the volume AZ to the default AZ.
disable_dhcp: false     # If true, disable DHCP

# Security configuration for Ops Director
trusted_certificates:      # bosh Trusted Certificates
vm_password_type: generate # 'generate' or 'bosh_default'

# Ops Director Config
ntp_servers: #CHANGEME       # Comma-separated list of NTP servers to use for VMs deployed by BOSH
metrics_ip:                  # IP address of Pivotal Ops Metrics if installed
resurrector_enabled: false   # Whether to enable BOSH VM resurrector
max_threads: 30              # Max threads count for deploying VMs
# TODO: Add ability to use external DB
bosh_database_type: internal # Type of DB to use (internal/external)
# TODO: Add ability to use s3 blobstore
bosh_blobstore_type: local   # Type of blobstore to use (local/s3)
os_keypair_name: #CHANGEME   # Keypair to use for bosh VMs
os_private_key:  #CHANGEME    # Private key for keypair

# Network configuration for Ops Director
icmp_checks_enabled: true  # Enable or disable ICMP checks

loggregator_endpoint_port:    # Loggegrator Port. Default is 443
company_name:                 # Company Name for Apps Manager

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
syslog_host:
syslog_port:
syslog_protocol:
enable_security_event_logging: false
syslog_drain_buffer_size: 10000

## Wildcard domain certs go here
# Optional. Will be generated if blank using ssl_termination_point below.
ssl_cert:
# Optional. Will be generated if blank using ssl_termination_point below.
ssl_private_key:
pcf_ert_saml_cert:
pcf_ert_saml_key:

haproxy_floating_ips: #CHANGEME  # Floating IPs allocated to HAProxy on OpenStack
haproxy_forward_tls: enable      # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca: #CHANGEME    # HAProxy will use the CA provided to verify the certificates provided by the router.
# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers:  #CHANGEME   # The recommended setting is "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".
haproxy_tls_ciphers: #CHANGEME   # The recommended setting is "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".

# See explanation here: https://docs.pivotal.io/pivotalcf/latest/customizing/config-er-vmware.html#app-security
security_acknowledgement: #CHANGEME # Must be set to 'X'
disable_http_proxy: false

## TCP routing and routing services
tcp_routing: disable                    # Enable/disable TCP routing (enable|disable)
tcp_routing_ports:                      # A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478 route_services: disable                 # Enable/disable route services (enable|disable)
ignore_ssl_cert_verification: false     # Whether to disable SSL cert verification for this environment
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454                # Applications Network Maximum Transmission Unit bytes

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd, and
# smtp_auth_mechanism must also be set.
smtp_address:
smtp_from:
smtp_port:
smtp_user:
smtp_pwd:
smtp_auth_mechanism: # (none|plain|cram-md5)

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:

## Deployment domain names
system_domain: #CHANGEME
apps_domain:   #CHANGEME

skip_cert_verify: false       # If true, disable SSL certificate verification for this environment.

disable_insecure_cookies: false # If true, disable insecure cookies on the router.

default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
allow_app_ssh_access: false             # Whether to allow SSH access to application instances

router_request_timeout_in_seconds: 900

ha_proxy_ips:           # Comma-separated list of static IPs
router_static_ips:      # Comma-separated list of static IPs
tcp_router_static_ips:  # Comma-separated list of static IPs
ssh_static_ips:         # Comma-separated list of static IPs

mysql_monitor_email: #CHANGEME # Email address to receive MySQL monitor notifications
mysql_backups: disable         # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

## Default resource configuration
consul_server_instances: 1
nats_instances: 1
nfs_server_instances: 1
mysql_proxy_instances: 1
mysql_instances: 1
backup_prepare_instances: 0
uaa_instances: 1
cloud_controller_instances: 1
ha_proxy_instances: 1
router_instances: 1
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 1
diego_database_instances: 1
diego_brain_instances: 1
diego_cell_instances: 3
doppler_instances: 1
loggregator_traffic_controller_instances: 1
tcp_router_instances: 1
syslog_adapter_instances: 3
route_services:
