groups:
- name: deploy
  jobs:
  - upload-opsman-image
  - create-infrastructure
  - configure-director
  - deploy-director
  - upload-ert
  - configure-ert
  - deploy-ert
  - wipe-env
- name: infra
  jobs:
  - create-infrastructure
- name: opsman
  jobs:
  - configure-director
  - deploy-director
- name: ert
  jobs:
  - upload-ert
  - configure-ert
  - deploy-ert
- name: teardown
  jobs:
  - wipe-env

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master

- name: ops-manager
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

- name: terraform-state
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{tf_aws_access_key}}
    secret_access_key: {{tf_aws_secret_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_output_bucket}}
    versioned_file: terraform.tfstate

jobs:
- name: upload-opsman-image
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: ops-manager
      tags: [ openstack ]
      params:
        globs:
        - "*.raw"
    - get: pcf-pipelines
  - task: upload
    file: pcf-pipelines/install-pcf/openstack/tasks/upload-opsman/task.yml
    tags: [ openstack ]
    params:
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OPSMAN_IMAGE: {{opsman_image}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}

- name: create-infrastructure
  serial_groups: [infra]
  ensure:
    put: terraform-state
    tags: [ openstack ]
    params:
      file: create-infrastructure-output/terraform.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [upload-opsman-image]
      tags: [ openstack ]
    - get: terraform-state
      tags: [ openstack ]
    - get: ops-manager
      tags: [ openstack ]
      params:
        globs: []
  - task: create-infrastructure
    tags: [ openstack ]
    file: pcf-pipelines/install-pcf/openstack/tasks/create-infrastructure/task.yml
    params:
      OS_PROJECT_NAME: {{os_project_name}}
      OS_USERNAME: {{os_username}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_RESOURCE_PREFIX: {{os_resource_prefix}}
      OPSMAN_PUBLIC_KEY: {{opsman_public_key}}
      OPSMAN_VOLUME_SIZE: {{opsman_volume_size}}
      INFRA_SUBNET_CIDR: {{infra_subnet_cidr}}
      ERT_SUBNET_CIDR: {{ert_subnet_cidr}}
      SERVICES_SUBNET_CIDR: {{services_subnet_cidr}}
      DYNAMIC_SERVICES_SUBNET_CIDR: {{dynamic_services_subnet_cidr}}
      INFRA_DNS: {{infra_dns}}
      ERT_DNS: {{ert_dns}}
      SERVICES_DNS: {{services_dns}}
      DYNAMIC_SERVICES_DNS: {{dynamic_services_dns}}
      EXTERNAL_NETWORK_ID: {{external_network_id}}
      EXTERNAL_NETWORK: {{external_network}}
      OPSMAN_FLAVOR: {{opsman_flavor}}

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: ops-manager
      tags: [ openstack ]
      params: {globs: []}
      passed: [create-infrastructure]
      trigger: true
  - task: configure-auth
    tags: [ openstack ]
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
  - task: configure
    tags: [ openstack ]
    file: pcf-pipelines/install-pcf/openstack/tasks/config-director/task.yml
    params:
      OPSMAN_URI: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_INTERFACE: {{os_interface}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_PASSWORD: {{os_password}}
      OS_USERNAME: {{os_username}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_REGION_NAME: {{os_region_name}}
      OS_TENANT: {{os_tenant}}
      OS_NETWORKING_MODEL: {{os_networking_model}}
      SECURITY_GROUP: {{security_group}}
      KEYPAIR_NAME: {{os_keypair_name}}
      PRIVATE_KEY: {{os_private_key}}
      IGNORE_SERVER_AZ: {{ignore_server_az}}
      DISABLE_DHCP: {{disable_dhcp}}
      API_SSL_CERT: {{pre_os_cacert}}
      VM_PASSWORD_TYPE: {{vm_password_type}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      BOSH_DATABASE_TYPE: {{bosh_database_type}}
      BOSH_BLOBSTORE_TYPE: {{bosh_blobstore_type}}
      INFRA_NETWORK: {{infra_network}}
      INFRA_SUBNET: {{infra_subnet_cidr}}
      INFRA_DNS: {{infra_dns}}
      INFRA_GATEWAY: {{infra_gateway}}
      INFRA_NW_AZS:  {{infra_nw_azs}}
      INFRA_RESERVED_IP_RANGES: {{infra_reserved_ip_ranges}}
      ERT_NETWORK: {{ert_network}}
      ERT_SUBNET: {{ert_subnet_cidr}}
      ERT_DNS: {{ert_dns}}
      ERT_GATEWAY: {{ert_gateway}}
      ERT_NW_AZS:  {{ert_nw_azs}}
      ERT_RESERVED_IP_RANGES: {{ert_reserved_ip_ranges}}
      SERVICES_NETWORK: {{services_network}}
      SERVICES_SUBNET: {{services_subnet_cidr}}
      SERVICES_DNS: {{services_dns}}
      SERVICES_GATEWAY: {{services_gateway}}
      SERVICES_NW_AZS:  {{services_nw_azs}}
      SERVICES_RESERVED_IP_RANGES: {{services_reserved_ip_ranges}}
      DYNAMIC_SERVICES_NETWORK: {{dynamic_services_network}}
      DYNAMIC_SERVICES_SUBNET: {{dynamic_services_subnet_cidr}}
      DYNAMIC_SERVICES_DNS: {{dynamic_services_dns}}
      DYNAMIC_SERVICES_GATEWAY: {{dynamic_services_gateway}}
      DYNAMIC_SERVICES_NW_AZS:  {{dynamic_services_nw_azs}}
      DYNAMIC_SERVICES_RESERVED_IP_RANGES: {{dynamic_services_reserved_ip_ranges}}
      AZ_01_NAME: {{az_01_name}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      NTP_SERVERS: {{ntp_servers}}
      METRICS_IP: {{metrics_ip}}
      RESURRECTOR_ENABLED: {{resurrector_enabled}}
      MAX_THREADS: {{max_threads}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: ops-manager
      tags: [ openstack ]
      params: {globs: []}
      passed: [configure-director]
      trigger: true
  - task: apply-changes
    tags: [ openstack ]
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: upload-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: pivnet-product
      tags: [ openstack ]
      resource: elastic-runtime
      params: {globs: ["cf*.pivotal"]}
    - get: ops-manager
      tags: [ openstack ]
      params: {globs: []}
      passed: [deploy-director]
      trigger: true
  - task: upload-tile
    tags: [ openstack ]
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""
      IAAS: openstack
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""

  - task: stage-tile
    tags: [ openstack ]
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""


- name: configure-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: pivnet-product
      tags: [ openstack ]
      resource: elastic-runtime
      params: {globs: []}
      passed: [upload-ert]
      trigger: true

  - task: configure
    tags: [ openstack ]
    file: pcf-pipelines/tasks/config-ert/task.yml
    params:
      IAAS: openstack
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      ERT_SINGLETON_JOB_AZ: {{ert_singleton_job_az}}
      DEPLOYMENT_NW_AZS: {{ert_nw_azs}}
      NETWORK_NAME: {{ert_network}}
      ENABLE_SECURITY_EVENT_LOGGING: {{enable_security_event_logging}}
      SYSLOG_HOST: {{syslog_host}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_PROTOCOL: {{syslog_protocol}}
      SYSLOG_DRAIN_BUFFER_SIZE: {{syslog_drain_buffer_size}}
      COMPANY_NAME: {{company_name}}
      AUTHENTICATION_MODE: {{authentication_mode}}
      LOGGREGATOR_ENDPOINT_PORT: {{loggregator_endpoint_port}}
      HAPROXY_FORWARD_TLS: {{haproxy_forward_tls}}
      HAPROXY_BACKEND_CA: {{haproxy_backend_ca}}
      ROUTER_TLS_CIPHERS: {{router_tls_ciphers}}
      HAPROXY_TLS_CIPHERS: {{haproxy_tls_ciphers}}
      HAPROXY_FLOATING_IPS: {{haproxy_floating_ips}}
      DISABLE_HTTP_PROXY: {{disable_http_proxy}}
      TCP_ROUTING: {{tcp_routing}}
      TCP_ROUTING_PORTS: {{tcp_routing_ports}}
      ROUTE_SERVICES: {{route_services}}
      IGNORE_SSL_CERT: {{ignore_ssl_cert_verification}}
      SMTP_FROM: {{smtp_from}}
      SMTP_ADDRESS: {{smtp_address}}
      SMTP_PORT: {{smtp_port}}
      SMTP_USER: {{smtp_user}}
      SMTP_PWD: {{smtp_pwd}}
      SMTP_ENABLE_STARTTLS_AUTO: {{smtp_enable_starttls_auto}}
      SMTP_AUTH_MECHANISM: {{smtp_auth_mechanism}}
      LDAP_URL: {{ldap_url}}
      LDAP_USER: {{ldap_user}}
      LDAP_PWD: {{ldap_pwd}}
      SEARCH_BASE: {{search_base}}
      SEARCH_FILTER: {{search_filter}}
      GROUP_SEARCH_BASE: {{group_search_base}}
      GROUP_SEARCH_FILTER: {{group_search_filter}}
      MAIL_ATTR_NAME: {{mail_attribute_name}}
      FIRST_NAME_ATTR: {{first_name_attribute}}
      LAST_NAME_ATTR: {{last_name_attribute}}
      SECURITY_ACKNOWLEDGEMENT: {{security_acknowledgement}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB: {{default_quota_memory_limit_mb}}
      DEFAULT_QUOTA_MAX_SERVICES_COUNT: {{default_quota_max_number_services}}
      HA_PROXY_IPS: {{ha_proxy_ips}}
      SKIP_CERT_VERIFY: {{skip_cert_verify}}
      DISABLE_INSECURE_COOKIES: {{disable_insecure_cookies}}
      ROUTER_STATIC_IPS: {{router_static_ips}}
      ROUTER_REQUEST_TIMEOUT_IN_SEC: {{router_request_timeout_in_seconds}}
      GARDEN_NETWORK_POOL_CIDR: {{garden_network_pool_cidr}}
      GARDEN_NETWORK_MTU: {{garden_network_mtu}}
      MYSQL_MONITOR_EMAIL: {{mysql_monitor_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      ALLOW_APP_SSH_ACCESS: {{allow_app_ssh_access}}
      TCP_ROUTER_STATIC_IPS: {{tcp_router_static_ips}}
      SSH_STATIC_IPS: {{ssh_static_ips}}
      MYSQL_STATIC_IPS: {{mysql_static_ips}}
      CONSUL_SERVER_INSTANCES: {{consul_server_instances}}
      CREDHUB_INSTANCES: {{credhub_instances}}
      NATS_INSTANCES: {{nats_instances}}
      NFS_SERVER_INSTANCES: {{nfs_server_instances}}
      MYSQL_PROXY_INSTANCES: {{mysql_proxy_instances}}
      MYSQL_INSTANCES: {{mysql_instances}}
      BACKUP_PREPARE_INSTANCES: {{backup_prepare_instances}}
      UAA_INSTANCES: {{uaa_instances}}
      CLOUD_CONTROLLER_INSTANCES: {{cloud_controller_instances}}
      HA_PROXY_INSTANCES: {{ha_proxy_instances}}
      ROUTER_INSTANCES: {{router_instances}}
      MYSQL_MONITOR_INSTANCES: {{mysql_monitor_instances}}
      CLOCK_GLOBAL_INSTANCES: {{clock_global_instances}}
      CLOUD_CONTROLLER_WORKER_INSTANCES: {{cloud_controller_worker_instances}}
      DIEGO_DATABASE_INSTANCES: {{diego_database_instances}}
      DIEGO_BRAIN_INSTANCES: {{diego_brain_instances}}
      DIEGO_CELL_INSTANCES: {{diego_cell_instances}}
      DOPPLER_INSTANCES: {{doppler_instances}}
      LOGGREGATOR_TRAFFICCONTROLLER_INSTANCES: {{loggregator_trafficcontroller_instances}}
      TCP_ROUTER_INSTANCES: {{tcp_router_instances}}
      SYSLOG_ADAPTER_INSTANCES: {{syslog_adapter_instances}}
      SYSLOG_SCHEDULER_INSTANCES: {{syslog_scheduler_instances}}
      INTERNET_CONNECTED: {{internet_connected}}
      CONTAINER_NETWORKING_NW_CIDR: {{container_networking_nw_cidr}}
      CREDUB_ENCRYPTION_KEY_NAME1: {{credhub_encryption_key_name1}}
      CREDUB_ENCRYPTION_KEY_SECRET1: {{credhub_encryption_key_secret1}}
      CREDUB_ENCRYPTION_KEY_NAME2: {{credhub_encryption_key_name2}}
      CREDUB_ENCRYPTION_KEY_SECRET2: {{credhub_encryption_key_secret2}}
      CREDUB_ENCRYPTION_KEY_NAME3: {{credhub_encryption_key_name3}}
      CREDUB_ENCRYPTION_KEY_SECRET3: {{credhub_encryption_key_secret3}}
      CREDHUB_PRIMARY_ENCRYPTION_NAME: {{credhub_primary_encryption_name}}
      SAML_SSL_CERT: {{pcf_ert_saml_cert}}
      SAML_SSL_PRIVATE_KEY: {{pcf_ert_saml_key}}
      ROUTING_TLS_TERMINATION: {{routing_tls_termination}}
      ROUTING_CUSTOM_CA_CERTIFICATES: {{routing_custom_ca_certificates}}
      POE_SSL_NAME1: {{poe_ssl_name1}}
      POE_SSL_CERT1: {{poe_ssl_cert1}}
      POE_SSL_KEY1: {{poe_ssl_key1}}
      POE_SSL_NAME2: {{poe_ssl_name2}}
      POE_SSL_CERT2: {{poe_ssl_cert2}}
      POE_SSL_KEY2: {{poe_ssl_key2}}
      POE_SSL_NAME3: {{poe_ssl_name3}}
      POE_SSL_CERT3: {{poe_ssl_cert3}}
      POE_SSL_KEY3: {{poe_ssl_key3}}
      TCP_ROUTER_NSX_SECURITY_GROUP: ""
      TCP_ROUTER_NSX_LB_EDGE_NAME: ""
      TCP_ROUTER_NSX_LB_POOL_NAME: ""
      TCP_ROUTER_NSX_LB_SECURITY_GROUP: ""
      TCP_ROUTER_NSX_LB_PORT: ""
      ROUTER_NSX_SECURITY_GROUP: ""
      ROUTER_NSX_LB_EDGE_NAME: ""
      ROUTER_NSX_LB_POOL_NAME: ""
      ROUTER_NSX_LB_SECURITY_GROUP: ""
      ROUTER_NSX_LB_PORT: ""
      DIEGO_BRAIN_NSX_SECURITY_GROUP: ""
      DIEGO_BRAIN_NSX_LB_EDGE_NAME: ""
      DIEGO_BRAIN_NSX_LB_POOL_NAME: ""
      DIEGO_BRAIN_NSX_LB_SECURITY_GROUP: ""
      DIEGO_BRAIN_NSX_LB_PORT: ""
      MYSQL_NSX_SECURITY_GROUP: ""
      MYSQL_NSX_LB_EDGE_NAME: ""
      MYSQL_NSX_LB_POOL_NAME: ""
      MYSQL_NSX_LB_SECURITY_GROUP: ""
      MYSQL_NSX_LB_PORT: ""
      HA_PROXY_LB_NAME: ""
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""


- name: deploy-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: pivnet-product
      tags: [ openstack ]
      resource: elastic-runtime
      params: {globs: []}
      passed: [configure-ert]
      trigger: true

  - task: deploy
    tags: [ openstack ]
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""


- name: wipe-env
  serial_groups: [infra]
  ensure:
    put: terraform-state
    tags: [ openstack ]
    params:
      file: wipe-output/terraform.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
      tags: [ openstack ]
    - get: terraform-state
      tags: [ openstack ]
  - task: wipe-env
    tags: [ openstack ]
    file: pcf-pipelines/install-pcf/openstack/tasks/wipe-env/task.yml
    params:
      OS_PROJECT_NAME: {{os_project_name}}
      OS_USERNAME: {{os_username}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OPSMAN_URI: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
