groups:
- name: deploy
  jobs:
  - create-infrastructure
  - deploy-opsman
  - deploy-director
  - upload-ert
  - configure-ert
  - deploy-ert
- name: infra
  jobs:
  - create-infrastructure
- name: opsman
  jobs:
  - deploy-opsman
  - deploy-director
- name: ert
  jobs:
  - upload-ert
  - configure-ert
  - deploy-ert
- name: teardown
  jobs:
  - wipe-env

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: http://github.com/pivotal-cf/pcf-pipelines.git

- name: ops-manager
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
- name: create-infrastructure
  serial_groups: [infra]
  plan:
  - get: pcf-pipelines
  - task: create-infrastructure
    file: pcf-pipelines/install-pcf/openstack/tasks/create-infrastructure/task.yml
    params:
      EXTERNAL_NETWORK: {{external_network}}
      INFRA_NETWORK: {{infra_network}}
      INFRA_SUBNET: {{infra_subnet}}
      INFRA_DNS: {{infra_dns}}
      ERT_NETWORK: {{ert_network}}
      ERT_SUBNET: {{ert_subnet}}
      SERVICES_NETWORK: {{services_network}}
      SERVICES_SUBNET: {{services_subnet}}
      DYNAMIC_SERVICES_NETWORK: {{dynamic_services_network}}
      DYNAMIC_SERVICES_SUBNET: {{dynamic_services_subnet}}
      ADMIN_ROUTER: {{admin_router}}
      SECURITY_GROUP: {{security_group}}
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}

- name: deploy-opsman
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: ops-manager
      params:
        globs:
        - "*.raw"
    - get: pcf-pipelines
  - task: upload
    file: pcf-pipelines/install-pcf/openstack/tasks/upload-opsman/task.yml
    params:
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OPSMAN_IMAGE: {{opsman_image}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}
  - task: deploy
    file: pcf-pipelines/install-pcf/openstack/tasks/deploy-opsman/task.yml
    params:
      EXTERNAL_NETWORK: {{external_network}}
      INFRA_NETWORK: {{infra_network}}
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}
      OPSMAN_IMAGE: {{opsman_image}}
      SECURITY_GROUP: {{security_group}}
      OPSMAN_KEY: {{opsman_key}}
      OPSMAN_FLAVOR: {{opsman_flavor}}
      OPSMAN_FLOATING_IP: {{opsman_floating_ip}}
      OPSMAN_VM_NAME: {{opsman_vm_name}}
  - task: configure-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: ops-manager
      params: {globs: []}
      passed: [deploy-opsman]
      trigger: true
  - task: configure
    file: pcf-pipelines/install-pcf/openstack/tasks/config-director/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_INTERFACE: {{os_interface}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_PASSWORD: {{os_password}}
      OS_USERNAME: {{os_username}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_REGION_NAME: {{os_region_name}}
      OS_TENANT: {{os_tenant}}
      SECURITY_GROUP: {{security_group}}
      KEYPAIR_NAME: {{os_keypair_name}}
      PRIVATE_KEY: {{os_private_key}}
      IGNORE_SERVER_AZ: {{ignore_server_az}}
      DISABLE_DHCP: {{disable_dhcp}}
      API_SSL_CERT: {{pre_os_cacert}}
      VM_PASSWORD_TYPE: {{vm_password_type}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      BOSH_DATABASE_TYPE: {{bosh_database_type}}
      BOSH_BLOBSTORE_TYPE: {{bosh_blobstore_type}}
      INFRA_NETWORK: {{infra_network}}
      INFRA_SUBNET: {{infra_subnet}}
      INFRA_DNS: {{infra_dns}}
      INFRA_GATEWAY: {{infra_gateway}}
      INFRA_NW_AZS:  {{infra_nw_azs}}
      INFRA_RESERVED_IP_RANGES: {{infra_reserved_ip_ranges}}
      ERT_NETWORK: {{ert_network}}
      ERT_SUBNET: {{ert_subnet}}
      ERT_DNS: {{ert_dns}}
      ERT_GATEWAY: {{ert_gateway}}
      ERT_NW_AZS:  {{ert_nw_azs}}
      ERT_RESERVED_IP_RANGES: {{ert_reserved_ip_ranges}}
      SERVICES_NETWORK: {{services_network}}
      SERVICES_SUBNET: {{services_subnet}}
      SERVICES_DNS: {{services_dns}}
      SERVICES_GATEWAY: {{services_gateway}}
      SERVICES_NW_AZS:  {{services_nw_azs}}
      SERVICES_RESERVED_IP_RANGES: {{services_reserved_ip_ranges}}
      DYNAMIC_SERVICES_NETWORK: {{dynamic_services_network}}
      DYNAMIC_SERVICES_SUBNET: {{dynamic_services_subnet}}
      DYNAMIC_SERVICES_DNS: {{dynamic_services_dns}}
      DYNAMIC_SERVICES_GATEWAY: {{dynamic_services_gateway}}
      DYNAMIC_SERVICES_NW_AZS:  {{dynamic_services_nw_azs}}
      DYNAMIC_SERVICES_RESERVED_IP_RANGES: {{dynamic_services_reserved_ip_ranges}}
      AZ_01_NAME: {{az_01_name}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      NTP_SERVERS: {{ntp_servers}}
      METRICS_IP: {{metrics_ip}}
      RESURRECTOR_ENABLED: {{resurrector_enabled}}
      MAX_THREADS: {{max_threads}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: ops-manager
      params: {globs: []}
      passed: [configure-director]
      trigger: true
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: upload-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["*.pivotal"]}
    - get: ops-manager
      params: {globs: []}
      passed: [deploy-director]
      trigger: true
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""
      IAAS: openstack
  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      PRODUCT_NAME: cf

- name: deploy-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["*.pivotal"]}
      passed: [upload-ert]
      trigger: true

  - task: configure
    file: pcf-pipelines/tasks/config-ert/task.yml
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      ERT_SINGLETON_JOB_AZ: {{ert_singleton_job_az}}
      DEPLOYMENT_NW_AZS: {{ert_nw_azs}}
      NETWORK_NAME: {{ert_network}}
      ENABLE_SECURITY_EVENT_LOGGING: {{enable_security_event_logging}}
      SYSLOG_HOST: {{syslog_host}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_PROTOCOL: {{syslog_protocol}}
      SYSLOG_DRAIN_BUFFER_SIZE: {{syslog_drain_buffer_size}}
      COMPANY_NAME: {{company_name}}
      AUTHENTICATION_MODE: {{authentication_mode}}
      LOGGREGATOR_ENDPOINT_PORT: {{loggregator_endpoint_port}}
      SSL_TERMINATION: {{ssl_termination_point}}
      SSL_CERT: {{ssl_cert}}
      SSL_PRIVATE_KEY: {{ssl_private_key}}
      DISABLE_HTTP_PROXY: {{disable_http_proxy}}
      TCP_ROUTING: {{tcp_routing}}
      TCP_ROUTING_PORTS: {{tcp_routing_ports}}
      ROUTE_SERVICES: {{route_services}}
      IGNORE_SSL_CERT: {{ignore_ssl_cert_verification}}
      SMTP_FROM: {{smtp_from}}
      SMTP_ADDRESS: {{smtp_address}}
      SMTP_PORT: {{smtp_port}}
      SMTP_USER: {{smtp_user}}
      SMTP_PWD: {{smtp_pwd}}
      SMTP_AUTH_MECHANISM: {{smtp_auth_mechanism}}
      LDAP_URL: {{ldap_url}}
      LDAP_USER: {{ldap_user}}
      LDAP_PWD: {{ldap_pwd}}
      SEARCH_BASE: {{search_base}}
      SEARCH_FILTER: {{search_filter}}
      GROUP_SEARCH_BASE: {{group_search_base}}
      GROUP_SEARCH_FILTER: {{group_search_filter}}
      MAIL_ATTR_NAME: {{mail_attribute_name}}
      FIRST_NAME_ATTR: {{first_name_attribute}}
      LAST_NAME_ATTR: {{last_name_attribute}}
      SECURITY_ACKNOWLEDGEMENT: {{security_acknowledgement}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB: {{default_quota_memory_limit_mb}}
      DEFAULT_QUOTA_MAX_SERVICES_COUNT: {{default_quota_max_number_services}}
      HA_PROXY_IPS: {{ha_proxy_ips}}
      SKIP_CERT_VERIFY: {{skip_cert_verify}}
      DISABLE_INSECURE_COOKIES: {{disable_insecure_cookies}}
      ROUTER_STATIC_IPS: {{router_static_ips}}
      ROUTER_REQUEST_TIMEOUT_IN_SEC: {{router_request_timeout_in_seconds}}
      GARDEN_NETWORK_POOL_CIDR: {{garden_network_pool_cidr}}
      GARDEN_NETWORK_MTU: {{garden_network_mtu}}
      MYSQL_MONITOR_EMAIL: {{mysql_monitor_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      ALLOW_APP_SSH_ACCESS: {{allow_app_ssh_access}}
      TCP_ROUTER_STATIC_IPS: {{tcp_router_static_ips}}
      SSH_STATIC_IPS: {{ssh_static_ips}}
      CONSUL_SERVER_INSTANCES: {{consul_server_instances}}
      NATS_INSTANCES: {{nats_instances}}
      ETCD_TLS_SERVER_INSTANCES: {{etcd_tls_server_instances}}
      NFS_SERVER_INSTANCES: {{nfs_server_instances}}
      MYSQL_PROXY_INSTANCES: {{mysql_proxy_instances}}
      MYSQL_INSTANCES: {{mysql_instances}}
      BACKUP_PREPARE_INSTANCES: {{backup_prepare_instances}}
      CCDB_INSTANCES: {{ccdb_instances}}
      UAADB_INSTANCES: {{uaadb_instances}}
      UAA_INSTANCES: {{uaa_instances}}
      CLOUD_CONTROLLER_INSTANCES: {{cloud_controller_instances}}
      HA_PROXY_INSTANCES: {{ha_proxy_instances}}
      ROUTER_INSTANCES: {{router_instances}}
      MYSQL_MONITOR_INSTANCES: {{mysql_monitor_instances}}
      CLOCK_GLOBAL_INSTANCES: {{clock_global_instances}}
      CLOUD_CONTROLLER_WORKER_INSTANCES: {{cloud_controller_worker_instances}}
      DIEGO_DATABASE_INSTANCES: {{diego_database_instances}}
      DIEGO_BRAIN_INSTANCES: {{diego_brain_instances}}
      DIEGO_CELL_INSTANCES: {{diego_cell_instances}}
      DOPPLER_INSTANCES: {{doppler_instances}}
      LOGGREGATOR_TC_INSTANCES: {{loggregator_traffic_controller_instances}}
      TCP_ROUTER_INSTANCES: {{tcp_router_instances}}
      SYSLOG_ADAPTER_INSTANCES: {{syslog_adapter_instances}}
      SYSLOG_SCHEDULER_INSTANCES: {{syslog_scheduler_instances}}

  - task: deploy
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: wipe-env
  serial_groups: [infra]
  plan:
  - get: pcf-pipelines
  - task: wipe-env
    file: pcf-pipelines/install-pcf/openstack/tasks/wipe-env/task.yml
    params:
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      EXTERNAL_NETWORK: {{external_network}}
      INFRA_NETWORK: {{infra_network}}
      ERT_NETWORK: {{ert_network}}
      SERVICES_NETWORK: {{services_network}}
      DYNAMIC_SERVICES_NETWORK: {{dynamic_services_network}}
      OS_KEYPAIR_NAME: {{os_keypair_name}}
      SECURITY_GROUP: {{security_group}}
      ADMIN_ROUTER: {{admin_router}}
      OPSMAN_FLOATING_IP: {{opsman_floating_ip}}
      OPSMAN_VM_NAME: {{opsman_vm_name}}
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}
