# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}}

- name: run-time-window
  type: time
  source:
    interval: {{automatic_updates_time_window_interval}}
    start: {{automatic_updates_time_window_start}}
    stop: {{automatic_updates_time_window_stop}}
    location: {{automatic_updates_time_window_timezone}}

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: tool-pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}}

- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: {{pipeline_version_compatibility}}

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

jobs:
- name: time-window-gate
  plan:
  - get: run-time-window
    trigger: true

- name: upgrade-opsmgr
  plan:
  - aggregate:
    - get: pcf-pipelines-tarball
    - get: govc
    - get: tool-om
      globs: om-linux
    - get: tool-pivnet-cli
      params:
        globs:
        - "pivnet-linux-amd64-*"
    - get: pivnet-opsmgr
      passed: [time-window-gate]
      trigger: {{enable_automatic_updates}} 
      params:
        globs:
        - "*.ova"

  - task: tarball-unpack
    config:
      inputs: [ { name: pcf-pipelines-tarball } ]
      outputs: [ { name: pcf-pipelines } ]
      platform: linux
      image_resource: { type: docker-image, source: {repository: cloudfoundry/cflinuxfs2} }
      run: { path: tar, args: [ "-xvzf", "pcf-pipelines-tarball/pcf-pipelines.tgz" ] }

  - aggregate:
    - task: export-opsmgr-settings
      file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
      params:
        OPSMAN_USERNAME: {{opsman_admin_username}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_URI: {{opsman_uri}}
        OPSMAN_SETTINGS_FILENAME: installation.zip
    - task: exported-opsmgr-diagnostic-report
      file: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.yml
      params:
        OPSMAN_USERNAME: {{opsman_admin_username}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_URI: {{opsman_uri}}

  - task: deploy-opsman-vm
    file: pcf-pipelines/tasks/deploy-opsman-vm/task.yml
    params:
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
      GOVC_USERNAME: {{vcenter_username}}
      GOVC_PASSWORD: {{vcenter_password}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_CLUSTER: {{vcenter_cluster}}
      GOVC_RESOURCE_POOL: {{vcenter_resource_pool}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_URL: {{vcenter_url}}
      OPSMAN_IP: {{opsman_ip}}
      NETMASK: {{netmask}}
      GATEWAY: {{gateway}}
      DNS: {{dns}}
      NTP: {{ntp}}
      OPSMAN_NETWORK: {{opsman_network}}
      OPSMAN_VM_FOLDER: {{opsman_vm_folder}}
      OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}

  - task: import-opsmgr
    file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip

  - task: download-stemcells
    file: pcf-pipelines/tasks/download-pivnet-stemcells/task.yml
    params:
      API_TOKEN: {{pivnet_token}}
      IAAS_TYPE: {{iaas_type}}

  - task: restore-stemcells
    file: pcf-pipelines/tasks/restore-stemcells/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}

      # todo discuss the order for calling this task
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
