resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: v0.26.1

- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: terraform-state
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    versioned_file: terraform.tfstate

- name: pivnet-elastic-runtime
  type: pivnet
  check_every: 4h
  source:
    api_token: {{PIVNET_TOKEN}}
    product_slug: elastic-runtime
    product_version: 1\.10\.*
    sort_by: semver

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines
    branch: master

- name: stemcell-downloader
  type: github-release
  source:
    user: pivotal-cf
    repository: pcf-product-stemcell-downloader
    access_token: {{GITHUB_TOKEN}}

jobs:
- name: aws-pcf-prepare
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines 
  - task: aws-pcf-prepare
    file: pcf-pipelines/tasks/install-pcf-aws/prepare-aws/task.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
      TF_VAR_route53_zone_id: {{ROUTE_53_ZONE_ID}}
      TF_VAR_vpc_cidr: {{TF_VAR_vpc_cidr}}
      TF_VAR_public_subnet_cidr_az1: {{TF_VAR_public_subnet_cidr_az1}}
      TF_VAR_public_subnet_cidr_az2: {{TF_VAR_public_subnet_cidr_az2}}
      TF_VAR_public_subnet_cidr_az3: {{TF_VAR_public_subnet_cidr_az3}}
      TF_VAR_ert_subnet_cidr_az1: {{TF_VAR_ert_subnet_cidr_az1}}
      TF_VAR_ert_subnet_cidr_az2: {{TF_VAR_ert_subnet_cidr_az2}}
      TF_VAR_ert_subnet_cidr_az3: {{TF_VAR_ert_subnet_cidr_az3}}
      TF_VAR_services_subnet_cidr_az1: {{TF_VAR_services_subnet_cidr_az1}}
      TF_VAR_services_subnet_cidr_az2: {{TF_VAR_services_subnet_cidr_az2}}
      TF_VAR_services_subnet_cidr_az3: {{TF_VAR_services_subnet_cidr_az3}}
      TF_VAR_infra_subnet_cidr_az1: {{TF_VAR_infra_subnet_cidr_az1}}
      TF_VAR_rds_subnet_cidr_az1: {{TF_VAR_rds_subnet_cidr_az1}}
      TF_VAR_rds_subnet_cidr_az2: {{TF_VAR_rds_subnet_cidr_az2}}
      TF_VAR_rds_subnet_cidr_az3: {{TF_VAR_rds_subnet_cidr_az3}}
      TF_VAR_opsman_ip_az1: {{TF_VAR_opsman_ip_az1}}
      TF_VAR_nat_ip_az1: {{TF_VAR_nat_ip_az1}}
      TF_VAR_nat_ip_az2: {{TF_VAR_nat_ip_az2}}
      TF_VAR_nat_ip_az3: {{TF_VAR_nat_ip_az3}}
    ensure:
      put: terraform-state
      params:
        file: terraform-state/terraform.tfstate

- name: config-opsman
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines 
      trigger: true
      passed: [aws-pcf-prepare]
  - task: config-opsman
    file: pcf-pipelines/tasks/install-pcf-aws/config-opsman/task.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: config-director
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines 
      trigger: true
      passed: [config-opsman]
    - get: terraform-state
  - task: config-director
    file: pcf-pipelines/tasks/install-pcf-aws/config-director/task.yml
    params:
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AWS_KEY_NAME: {{TF_VAR_aws_key_name}}
      PEM: {{PEM}}
      AWS_REGION: {{TF_VAR_aws_region}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      ert_subnet_reserved_ranges_z1: {{ert_subnet_reserved_ranges_z1}}
      ert_subnet_reserved_ranges_z2: {{ert_subnet_reserved_ranges_z2}}
      ert_subnet_reserved_ranges_z3: {{ert_subnet_reserved_ranges_z3}}
      services_subnet_reserved_ranges_z1: {{services_subnet_reserved_ranges_z1}}
      services_subnet_reserved_ranges_z2: {{services_subnet_reserved_ranges_z2}}
      services_subnet_reserved_ranges_z3: {{services_subnet_reserved_ranges_z3}}
      infra_subnet_reserved_ranges_z1: {{infra_subnet_reserved_ranges_z1}}

- name: deploy-director
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [config-director]
  - task: deploy-director
    file: pcf-pipelines/tasks/install-pcf-aws/deploy-director/task.yml
    params:
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_opsman_admin: {{OPSMAN_USER}}
      pcf_opsman_admin_passwd: {{OPSMAN_PASSWORD}}

- name: import-stemcell
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [deploy-director]
    - get: stemcell-downloader
      params:
        globs: [stemcell-downloader-linux]
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      params:
        globs:
        - "*pivotal"
  - task: upload-stemcell
    file: pcf-pipelines/tasks/upload-stemcell/task.yml
    params:
      PRODUCT: cf
      IAAS_TYPE: aws
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_URI: {{OPSMAN_URI}}

- name: upload-ert
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines 
      trigger: true
      passed: [import-stemcell]
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      passed: [import-stemcell]
      params:
        globs:
        - "*pivotal"
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product/task.yml
    params:
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      TILE_UPLOAD_TIMEOUT: {{TILE_UPLOAD_TIMEOUT}}
  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      PRODUCT_NAME: cf

- name: deploy-ert
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines 
      trigger: true
      passed: [upload-ert]
    - get: terraform-state

  - task: prepare-rds
    file: pcf-pipelines/tasks/install-pcf-aws/prepare-rds/task.yml
    params:
      PEM: {{PEM}}
      ERT_DOMAIN: {{ERT_DOMAIN}}

  - task: configure-json
    file: pcf-pipelines/tasks/install-ert/configure-json/task.yml
    params:
      pcf_iaas: aws
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_opsman_admin: {{OPSMAN_USER}}
      pcf_opsman_admin_passwd: {{OPSMAN_PASSWORD}}
      pcf_ert_ssl_cert: {{ERT_SSL_CERT}}
      pcf_ert_ssl_key: {{ERT_SSL_KEY}}
      pcf_az_1: {{TF_VAR_az1}}
      pcf_az_2: {{TF_VAR_az2}}
      pcf_az_3: {{TF_VAR_az3}}
      terraform_template: default
      terraform_prefix: {{TF_VAR_environment}}
      bucket: {{S3_OUTPUT_BUCKET}}
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      # IaaS Specific for GCP only
      gcp_proj_id:
      gcp_region:
      gcp_svc_acct_key:
      gcp_storage_access_key:
      gcp_storage_secret_key:
      # db credentials
      db_app_usage_service_username: {{TF_VAR_rds_db_username_appusage}}
      db_app_usage_service_password: {{TF_VAR_rds_db_password_appusage}}
      db_autoscale_username: {{TF_VAR_rds_db_username_autoscale}}
      db_autoscale_password: {{TF_VAR_rds_db_password_autoscale}}
      db_diego_username: {{TF_VAR_rds_db_username_diego}}
      db_diego_password: {{TF_VAR_rds_db_password_diego}}
      db_notifications_username: {{TF_VAR_rds_db_username_notifications}}
      db_notifications_password: {{TF_VAR_rds_db_password_notifications}}
      db_routing_username: {{TF_VAR_rds_db_username_routing}}
      db_routing_password: {{TF_VAR_rds_db_password_routing}}
      db_uaa_username: {{TF_VAR_rds_db_username_uaa}}
      db_uaa_password: {{TF_VAR_rds_db_password_uaa}}
      db_ccdb_username: {{TF_VAR_rds_db_username_ccdb}}
      db_ccdb_password: {{TF_VAR_rds_db_password_ccdb}}
      ert_sql_db_username: {{TF_VAR_rds_db_username_ertsql}}
      ert_sql_db_password: {{TF_VAR_rds_db_password_ertsql}}
      db_accountdb_username: {{TF_VAR_rds_db_username_account}}
      db_accountdb_password: {{TF_VAR_rds_db_password_account}}
      db_networkpolicyserverdb_username: {{TF_VAR_rds_db_username_networkpolicy}}
      db_networkpolicyserverdb_password: {{TF_VAR_rds_db_password_networkpolicy}}
      db_nfsvolumedb_username: {{TF_VAR_rds_db_username_nfsvolume}}
      db_nfsvolumedb_password: {{TF_VAR_rds_db_password_nfsvolume}}   

  - task: configure-ert
    file: pcf-pipelines/tasks/install-ert/configure-ert/task.yml
    params:
      pcf_iaas: aws
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_opsman_admin: {{OPSMAN_USER}}
      pcf_opsman_admin_passwd: {{OPSMAN_PASSWORD}}

  - task: deploy-ert
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: aws-pcf-destroy
  serial: true
  ensure:
    put: terraform-state
    params:
      file: terraform-state/terraform.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
  - task: aws-pcf-destroy
    file: pcf-pipelines/tasks/install-pcf-aws/destroy-aws/task.yml
    params:
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_rds_db_username: {{TF_VAR_rds_db_username}}
      TF_VAR_rds_db_password: {{TF_VAR_rds_db_password}}
      TF_VAR_environment: {{TF_VAR_environment}}
      TF_VAR_opsman_ami: {{TF_VAR_opsman_ami}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
      TF_VAR_route53_zone_id: {{ROUTE_53_ZONE_ID}}
      TF_VAR_vpc_cidr: {{TF_VAR_vpc_cidr}}
      TF_VAR_public_subnet_cidr_az1: {{TF_VAR_public_subnet_cidr_az1}}
      TF_VAR_public_subnet_cidr_az2: {{TF_VAR_public_subnet_cidr_az2}}
      TF_VAR_public_subnet_cidr_az3: {{TF_VAR_public_subnet_cidr_az3}}
      TF_VAR_ert_subnet_cidr_az1: {{TF_VAR_ert_subnet_cidr_az1}}
      TF_VAR_ert_subnet_cidr_az2: {{TF_VAR_ert_subnet_cidr_az2}}
      TF_VAR_ert_subnet_cidr_az3: {{TF_VAR_ert_subnet_cidr_az3}}
      TF_VAR_services_subnet_cidr_az1: {{TF_VAR_services_subnet_cidr_az1}}
      TF_VAR_services_subnet_cidr_az2: {{TF_VAR_services_subnet_cidr_az2}}
      TF_VAR_services_subnet_cidr_az3: {{TF_VAR_services_subnet_cidr_az3}}
      TF_VAR_infra_subnet_cidr_az1: {{TF_VAR_infra_subnet_cidr_az1}}
      TF_VAR_rds_subnet_cidr_az1: {{TF_VAR_rds_subnet_cidr_az1}}
      TF_VAR_rds_subnet_cidr_az2: {{TF_VAR_rds_subnet_cidr_az2}}
      TF_VAR_rds_subnet_cidr_az3: {{TF_VAR_rds_subnet_cidr_az3}}
  - put: terraform-state
    params:
      file: terraform-state-output/terraform.tfstate
