# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

- name: schedule
  type: time
  source:
    interval: 30m
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: pivnet-opsmgr
    params: { globs: [] }

- name: upgrade-opsmgr
  serial: true
  plan:
  - aggregate:
    - get: pivnet-opsmgr
      passed: [regulator]
      trigger: true
      params:
        globs:
        - "*AWS.yml"
    - get: pcf-pipelines
  - task: wait-opsman-clear
    file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}

  - aggregate:
    - task: export-opsmgr-settings
      file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
      params:
        OPSMAN_CLIENT_ID: {{opsman_client_id}}
        OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        OPSMAN_SETTINGS_FILENAME: installation.zip
    - task: exported-opsmgr-diagnostic-report
      file: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.yml
      params:
        OPSMAN_CLIENT_ID: {{opsman_client_id}}
        OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}

  - task: create-cliaas-config
    file: pcf-pipelines/upgrade-ops-manager/aws/tasks/create-cliaas-config/task.yml
    params:
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_REGION: {{aws_region}}
      AWS_VPC_ID: {{aws_vpc_id}}

  - task: replace-opsman-vm
    file: pcf-pipelines/tasks/replace-vm/task.yml
    params:
      VM_IDENTIFIER: {{existing_opsman_vm_name}}
      VM_DISK_SIZE_GB: ""

  - task: import-opsmgr-settings
    file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
