CREATE DATABASE IF NOT EXISTS uaa;
CREATE DATABASE IF NOT EXISTS ccdb;
CREATE DATABASE IF NOT EXISTS notifications;
CREATE DATABASE IF NOT EXISTS autoscale;
CREATE DATABASE IF NOT EXISTS app_usage_service;
CREATE DATABASE IF NOT EXISTS console;
CREATE DATABASE IF NOT EXISTS routing;
CREATE DATABASE IF NOT EXISTS diego;
