# GCP project to create the infrastructure in
gcp_project_id: CHANGEME

# GCP credentials JSON. The service account must have the Editor role.
gcp_service_account_key: |
  CHANGEME

# Identifier to prepend to GCP infrastructure names/labels
gcp_resource_prefix: concourse-terraform

# GCP region
gcp_region: us-central1

# GCP Zones
gcp_zone_1: us-central1-a
gcp_zone_2: us-central1-b
gcp_zone_3: us-central1-c

# GCP Interopable storage access key: https://console.cloud.google.com/storage/settings
gcp_storage_access_key: CHANGEME
gcp_storage_secret_key: CHANGEME

# S3 configuration for storage of terraform state. Terraform state files
# contain plaintext secrets; as such Minio is recommended to keep configuration
# local to Concourse: https://hub.docker.com/r/minio/minio
# docker run -e MINIO_ACCESS_KEY="example-access-key" -e MINIO_SECRET_KEY="example-secret-key" --network host minio/minio server /tmp
s3_endpoint: s3.amazonaws.com
s3_bucket_terraform: gcp-concourse
s3_access_key_id: CHANGEME
s3_secret_access_key: CHANGEME
s3_region: CHANGEME

git_private_key:

# Pivotal Network token: https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: CHANGEME

# Operations Manager credentials to set
pcf_opsman_admin_username: CHANGEME
pcf_opsman_admin_password: CHANGEME

# Elastic Runtime Domain
pcf_ert_domain: CHANGEME # This is the domain you will access ERT with
opsman_uri: CHANGEME # This should be your pcf_ert_domain with "opsman." as a prefix

# Elastic Runtime SSL configuration
# Set pcf_ert_ssl_cert to 'generate' if you'd like a self-signed cert to be
# made
pcf_ert_ssl_cert: generate
pcf_ert_ssl_key:

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable: none

# PCF Operations Manager minor version to install
opsman_major_minor_version: ^1\.10\..*$

# PCF Elastic Runtime minor version to install
ert_major_minor_version: ^1\.10\..*$

# DB Creds
# Usernames must be 16 characters or fewer
db_diego_username: CHANGEME
db_diego_password: CHANGEME
db_notifications_username: CHANGEME 
db_notifications_password: CHANGEME 
db_autoscale_username: CHANGEME 
db_autoscale_password: CHANGEME 
db_uaa_username: CHANGEME
db_uaa_password: CHANGEME
db_app_usage_service_username: CHANGEME 
db_app_usage_service_password: CHANGEME 
db_ccdb_username: CHANGEME
db_ccdb_password: CHANGEME
db_routing_username: CHANGEME
db_routing_password: CHANGEME

db_accountdb_username: CHANGEME
db_accountdb_password: CHANGEME
db_networkpolicyserverdb_username: CHANGEME
db_networkpolicyserverdb_password: CHANGEME
db_nfsvolumedb_username: CHANGEME
db_nfsvolumedb_password: CHANGEME
db_silk_username:
db_silk_password:
db_locket_username:
db_locket_password:

mysql_monitor_recipient_email:  # Email address for sending mysql monitor notifications
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:
