groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master
    username: {{github_token}}

- name: terraform-state
  type: s3
  source:
    region_name: {{s3_region}}
    bucket: {{s3_bucket_terraform}}
    endpoint: {{s3_endpoint}}
    regexp: "terraform/terraform-(.*).tfstate"
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: tfstate-version
  type: semver
  source:
   driver: s3
   bucket: {{s3_bucket_terraform}}
   key: terraform/version
   access_key_id: {{s3_access_key_id}}
   secret_access_key: {{s3_secret_access_key}}
   endpoint: {{s3_endpoint}}
   initial_version: 0.0.0
   region_name: {{s3_region}}

- name: pivnet-opsmgr
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pivnet-elastic-runtime
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

jobs:
- name: wipe-env
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
    - get: tfstate-version
      params:
        bump: major
  - task: wipe
    file: pcf-pipelines/tasks/install-pcf-gcp/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
  - put: terraform-state
    params:
      file: wipe-output/*.tfstate
  - put: tfstate-version
    params:
      file: tfstate-version/version

- name: upload-opsman-image
  plan:
  - get: pcf-pipelines
  - get: pivnet-opsmgr
    trigger: true
    params:
      globs:
      - "*GCP.yml"
  - task: upload
    file: pcf-pipelines/tasks/install-pcf-gcp/upload-opsman/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: create-infrastructure
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [upload-opsman-image]
      params:
        globs:
        - "*GCP.yml"
    - get: tfstate-version
      params:
        bump: major
  - task: create-infrastructure
    file: pcf-pipelines/tasks/install-pcf-gcp/create-infrastructure/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      PCF_ERT_SSL_CERT: {{pcf_ert_ssl_cert}}
      PCF_ERT_SSL_KEY: {{pcf_ert_ssl_key}}
      ERT_SQL_DB_USERNAME: {{ert_sql_db_username}}
      ERT_SQL_DB_PASSWORD: {{ert_sql_db_password}}
    on_failure:
      task: rollback
      file: pcf-pipelines/tasks/install-pcf-gcp/rollback-create-infrastructure/task.yml
      params:
        GCP_PROJECT_ID: {{gcp_project_id}}
        GCP_REGION: {{gcp_region}}
        GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
  - put: terraform-state
    params:
      file: create-infrastructure-output/*.tfstate
  - put: tfstate-version
    params:
      file: tfstate-version/version

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: tool-om
      resource: tool-om-beta
      params:
        globs:
        - "om-linux"
  - task: check-opsman-dns
    file: pcf-pipelines/tasks/install-pcf-gcp/check-opsman-dns/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
  - task: configure-opsman-auth
    file: pcf-pipelines/tasks/install-pcf-gcp/config-opsman-auth/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
  - task: configure-director
    file: pcf-pipelines/tasks/install-pcf-gcp/config-director/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
      gcp_proj_id: {{gcp_project_id}}
      gcp_region: {{gcp_region}}
      gcp_zone_1: {{gcp_zone_1}}
      gcp_zone_2: {{gcp_zone_2}}
      gcp_zone_3: {{gcp_zone_3}}
      gcp_resource_prefix: {{gcp_resource_prefix}}
      gcp_svc_acct_key: {{gcp_service_account_key}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: tool-om
      params:
        globs:
        - "om-linux"
      trigger: true
      passed: [configure-director]
  - task: deploy-director
    file: pcf-pipelines/tasks/install-pcf-gcp/deploy-director/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}

- name: deploy-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      trigger: true
      passed: [deploy-director]
      params:
        globs:
        - "om-linux"
    - get: terraform-state

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product/task.yml
    params:
      OPSMAN_URI: {{pcf_ert_domain}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      TILE_UPLOAD_TIMEOUT: {{tile_upload_timeout}}

  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_URI: {{pcf_ert_domain}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      PRODUCT_NAME: cf

  - task: configure-json
    file: pcf-pipelines/tasks/install-ert/configure-json/task.yml
    params:
      pcf_iaas: gcp
      terraform_template: default
      pcf_ert_ssl_cert: "generate"
      pcf_ert_ssl_key: {{pcf_ert_ssl_key}}
      pcf_az_1: {{gcp_zone_1}}
      pcf_az_2: {{gcp_zone_2}}
      pcf_az_3: {{gcp_zone_3}}
      gcp_proj_id: {{gcp_project_id}}
      gcp_region: {{gcp_region}}
      gcp_storage_access_key: {{gcp_storage_access_key}}
      gcp_storage_secret_key: {{gcp_storage_secret_key}}
      gcp_svc_acct_key: {{gcp_service_account_key}}
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
      ert_sql_db_username: {{ert_sql_db_username}}
      ert_sql_db_password: {{ert_sql_db_password}}
      terraform_prefix: {{gcp_resource_prefix}}
      db_diego_username: {{db_diego_username}}
      db_diego_password: {{db_diego_password}}
      db_notifications_username: {{db_notifications_username}}
      db_notifications_password: {{db_notifications_password}}
      db_autoscale_username: {{db_autoscale_username}}
      db_autoscale_password: {{db_autoscale_password}}
      db_uaa_username: {{db_uaa_username}}
      db_uaa_password: {{db_uaa_password}}
      db_app_usage_service_username: {{db_app_usage_service_username}}
      db_app_usage_service_password: {{db_app_usage_service_password}}
      db_ccdb_username: {{db_ccdb_username}}
      db_ccdb_password: {{db_ccdb_password}}
      db_routing_username: {{db_routing_username}}
      db_routing_password: {{db_routing_password}}
      db_accountdb_username: {{db_accountdb_username}}
      db_accountdb_password: {{db_accountdb_password}}
      db_networkpolicyserverdb_username: {{db_networkpolicyserverdb_username}}
      db_networkpolicyserverdb_password: {{db_networkpolicyserverdb_password}}
      db_nfsvolumedb_username: {{db_nfsvolumedb_username}}
      db_nfsvolumedb_password: {{db_nfsvolumedb_password}}         
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      # aws specific
      bucket:
      TF_VAR_aws_access_key:
      TF_VAR_aws_secret_key:
      S3_ENDPOINT:

  - task: configure-ert
    file: pcf-pipelines/tasks/install-ert/configure-ert/task.yml
    params:
      pcf_iaas: gcp
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}

  - task: deploy-ert
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{pcf_ert_domain}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
