resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
## Uncomment the below snippet to only let the pipeline run between midnight and 1am central time.
## If a change is detected earlier the pipeline will start but be held up waiting for the time
## resource to become available.
## Also uncomment the fetching of the resource in the plan below.
#- name: run-time-window
#  type: time
#  source:
#    start: 12:00 AM
#    stop: 1:00 AM
#    location: America/Chicago
- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    region_name: us-west-1
    regexp: releases/v([\d\.]+)/cf-cli_.*_linux_x86-64.tgz

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/c0-ops/pcf-pipelines.git
    username: {{github_token}}
    password: x-oauth-basic
    branch: master

- name: binary-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Binary*

- name: dotnet-core-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: .NET*

- name: go-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Go*

- name: java-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Java*

- name: nodejs-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: NodeJS*

- name: php-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: PHP*

- name: python-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Python*

- name: ruby-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Ruby*

- name: staticfile-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Staticfile*

- name: tc-buildpack
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: tc*

jobs:
- name: update-binary-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: binary-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: binary_buildpack_latest

- name: update-dotnet-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: dotnet-core-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: dotnet_core_buildpack_offline_latest

- name: update-go-buildpack
  plan:
  - aggregate:
## Uncomment to limit when the pipeline can run
#   - get: run-time-window
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: go-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: go_buildpack_latest

- name: update-java-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: java-buildpack
      trigger: true
      params:
        globs:
        - "*offline*"
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: java_buildpack_offline_latest

- name: update-nodejs-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: nodejs-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: nodejs_buildpack_latest

- name: update-php-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: php-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: php_buildpack_latest

- name: update-python-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: python-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: python_buildpack_latest

- name: update-ruby-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: ruby-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: ruby_buildpack_latest

- name: update-staticfile-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: staticfile-buildpack
      trigger: true
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: staticfile_buildpack_latest

- name: update-tcserver-buildpack
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: tc-buildpack
      trigger: true
    params:
      globs:
      - "*offline*"
  - task: update
    file: pcf-pipelines/tasks/upgrade-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: tc_buildpack_latest
