# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
## Uncomment the below snippet to only let the pipeline run between midnight and 1am central time.
## If a change is detected earlier the pipeline will start but be held up waiting for the time
## resource to become available.
## Also uncomment the fetching of the resource in the plan below.
#- name: run-time-window
#  type: time
#  source:
#    start: 12:00 AM
#    stop: 1:00 AM
#    location: America/Chicago
- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    region_name: us-west-1
    regexp: releases/v([\d\.]+)/cf-cli_.*_linux_x86-64.tgz

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/c0-ops/pcf-pipelines.git
    branch: master

- name: binary-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Binary*

- name: dotnet-core-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: .NET*

- name: go-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Go*

- name: java-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Java*

- name: nodejs-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: NodeJS*

- name: php-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: PHP*

- name: python-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Python*

- name: ruby-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Ruby*

- name: staticfile-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: Staticfile*

- name: tc-buildpack
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: buildpacks
    product_version: tc*

jobs:
- name: stage-binary-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: binary-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: binary_buildpack_latest

- name: promote-binary-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: go-buildpack
      passed: [stage-binary-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: binary_buildpack_latest
      TARGET_BUILDPACK_NAME: binary_buildpack

- name: stage-dotnet-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: dotnet-core-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: dotnet_core_buildpack_offline_latest

- name: promote-dotnet-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: dotnet-buildpack
      passed: [stage-dotnet-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: dotnet_core_buildpack_offline_latest
      TARGET_BUILDPACK_NAME: dotnet_core_buildpack_offline

- name: stage-go-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: go-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: go_buildpack_latest

- name: promote-go-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: go-buildpack
      passed: [stage-go-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: go_buildpack_latest
      TARGET_BUILDPACK_NAME: go_buildpack

- name: stage-java-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: java-buildpack
      trigger: true
      params:
        globs:
        - "*offline*"
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: java_buildpack_offline_latest

- name: promote-java-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: java-buildpack
      passed: [stage-java-buildpack]
      trigger: false
      params:
        globs:
        - "*offline*"
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: java_buildpack_offline_latest
      TARGET_BUILDPACK_NAME: java_buildpack_offline

- name: stage-nodejs-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: nodejs-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: nodejs_buildpack_latest

- name: promote-nodejs-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: nodejs-buildpack
      passed: [stage-nodejs-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: nodejs_buildpack_latest
      TARGET_BUILDPACK_NAME: nodejs_buildpack

- name: stage-php-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: php-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: php_buildpack_latest

- name: promote-php-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: php-buildpack
      passed: [stage-php-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: php_buildpack_latest
      TARGET_BUILDPACK_NAME: php_buildpack

- name: stage-python-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: python-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: python_buildpack_latest

- name: promote-python-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: python-buildpack
      passed: [stage-python-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: python_buildpack_latest
      TARGET_BUILDPACK_NAME: python_buildpack

- name: stage-ruby-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: ruby-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: ruby_buildpack_latest

- name: promote-ruby-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: ruby-buildpack
      passed: [stage-ruby-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: ruby_buildpack_latest
      TARGET_BUILDPACK_NAME: ruby_buildpack

- name: stage-staticfile-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: staticfile-buildpack
      trigger: true
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: staticfile_buildpack_latest

- name: promote-staticfile-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: staticfile-buildpack
      passed: [stage-staticfile-buildpack]
      trigger: false
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: staticfile_buildpack_latest
      TARGET_BUILDPACK_NAME: staticfile_buildpack

- name: stage-tcserver-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: tc-buildpack
      trigger: true
      params:
        globs:
        - "*offline*"
  - task: stage
    file: pcf-pipelines/tasks/stage-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      BUILDPACK_NAME: tc_buildpack_latest

- name: promote-tcserver-buildpack
  serial_groups: [cc-api]
  plan:
  - aggregate:
    - get: cf-cli
    - get: pcf-pipelines
    - get: buildpack
      resource: tc-buildpack
      passed: [stage-tcserver-buildpack]
      trigger: false
      params:
        globs:
        - "*offline*"
  - task: promote
    file: pcf-pipelines/tasks/promote-buildpack/task.yml
    params:
      CF_API_URI: {{cf_api_uri}}
      CF_USERNAME: {{cf_user}}
      CF_PASSWORD: {{cf_password}}
      SOURCE_BUILDPACK_NAME: tc_buildpack_latest
      TARGET_BUILDPACK_NAME: tc_buildpack
