resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/c0-ops/pcf-pipelines.git
    branch: master

- name: pivnet-release
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    access_key_id: {{pivnet_aws_access_key}}
    secret_access_key: {{pivnet_aws_secret_key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0
    uri: https://github.com/c0-ops/pcf-pipelines
    username: {{github_token}}
    password: x-oauth-basic
    branch: version
    file: version

jobs:
- name: test
  plan:
  - get: pcf-pipelines
    trigger: true
  - task: test
    file: pcf-pipelines/ci/tasks/test.yml

- name: update-upgrade-ert
  plan:
  - get: pcf-pipelines
    trigger: true
    passed:
    - test
  - task: update-pipeline
    file: pcf-pipelines/ci/tasks/update_pipeline.yml
    params:
      PIPELINE_NAME: upgrade-ert
      PIPELINE_PATH: pcf-pipelines/upgrade-ert/pipeline.yml
      ATC_EXTERNAL_URL: {{atc_external_url}}
      ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
      ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
      ATC_TEAM_NAME: {{atc_team_name}}

      PIVNET_TOKEN: {{pivnet_token}}
      OPSMAN_ADMIN_USERNAME: {{opsman_admin_username}}
      OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      GITHUB_TOKEN: {{github_token}}
      IAAS_TYPE: {{iaas_type}}
      PIVNET_POLL_INTERVAL: {{pivnet_poll_interval}}
      OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}

- name: update-upgrade-buildpacks
  plan:
  - get: pcf-pipelines
    trigger: true
    passed:
    - test
  - task: update-pipeline
    file: pcf-pipelines/ci/tasks/update_pipeline.yml
    params:
      PIPELINE_NAME: upgrade-buildpacks
      PIPELINE_PATH: pcf-pipelines/upgrade-buildpacks/pipeline.yml
      ATC_EXTERNAL_URL: {{atc_external_url}}
      ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
      ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
      ATC_TEAM_NAME: {{atc_team_name}}

      PIVNET_TOKEN: {{pivnet_token}}
      PIVNET_POLL_INTERVAL: {{pivnet_poll_interval}}
      CF_API_URI: {{cf_api_uri}}
      CF_USER: {{cf_user}}
      CF_PASSWORD: {{cf_password}}

- name: rc
  plan:
  - get: pcf-pipelines
    trigger: true
    passed:
    - update-upgrade-ert
    - update-upgrade-buildpacks
  - put: version
    params: {pre: rc}

- name: publish-release
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: pcf-pipelines
      passed:
      - rc
  - task: create-pivnet-metadata
    file: pcf-pipelines/ci/tasks/create_pivnet_metadata.yml
  - task: create-release
    file: pcf-pipelines/ci/tasks/create_release.yml
  - put: pivnet-release
    params:
      metadata_file: pivnet-metadata/metadata.yml
      file_glob: pcf-pipelines-release-files/*
      s3_filepath_prefix: {{pivnet_s3_filepath_prefix}}
  - put: version
    params:
      bump: major
      pre: rc
