resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

- name: pivnet-rc
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    access_key_id: {{pivnet_aws_access_key}}
    secret_access_key: {{pivnet_aws_secret_key}}
    product_version: .*-rc\.\d+

- name: pivnet-release
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    access_key_id: {{pivnet_aws_access_key}}
    secret_access_key: {{pivnet_aws_secret_key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0
    uri: https://github.com/pivotal-cf/pcf-pipelines
    username: {{github_token}}
    password: x-oauth-basic
    branch: version
    file: version

- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    region_name: us-west-1
    regexp: releases/v([\d\.]+)/cf-cli_.*_linux_x86-64.tgz

- name: om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

jobs:
- name: test
  plan:
  - get: pcf-pipelines
    trigger: true
  - task: test
    file: pcf-pipelines/ci/tasks/test.yml

- name: publish-rc
  plan:
  - aggregate:
    - get: version
      params: {pre: rc}
    - get: pcf-pipelines
      trigger: true
      passed: [test]
    - get: cf-cli
    - get: om
      params:
        globs: [om-linux]

  - task: stamp-release-version
    file: pcf-pipelines/ci/tasks/stamp_release_version.yml

  - put: pcf-pipelines
    params:
      repository: pcf-pipelines-release
      tag: version/version
      tag_prefix: v

  - put: version
    params: {pre: rc}

  - task: create-pivnet-metadata
    file: pcf-pipelines/ci/tasks/create_pivnet_metadata.yml
    params:
      AVAILABILITY: Admins Only

  - task: create-release
    file: pcf-pipelines/ci/tasks/create_release.yml

  - put: pivnet-rc
    params:
      metadata_file: pivnet-metadata/metadata.yml
      file_glob: pcf-pipelines-release-files/*
      s3_filepath_prefix: {{pivnet_s3_filepath_prefix}}

- name: update-pipelines
  plan:
  - aggregate:
    - get: version
      passed: [publish-rc]
    - get: pcf-pipelines
      passed: [publish-rc]
    - get: pivnet-rc
      trigger: true 
      passed: [publish-rc]
    - get: cf-cli
    - get: om
      params:
        globs: [om-linux]

  - task: unpack-rc
    file: pcf-pipelines/tasks/unpack-tarball/task.yml
    input_mapping: { tarball: pivnet-rc }
    output_mapping: { unpacked_tarball: release }

  - task: update-ert-pipeline
    file: pcf-pipelines/ci/tasks/update_pipeline.yml
    params:
      <<: *update_pipeline_params
      PIPELINE_NAME: upgrade-ert
      PIPELINE_PATH: release/pcf-pipelines/upgrade-ert/pipeline.yml

  - task: update-buildpacks-pipeline
    file: pcf-pipelines/ci/tasks/update_pipeline.yml
    params:
      <<: *update_pipeline_params
      PIPELINE_NAME: upgrade-buildpacks
      PIPELINE_PATH: release/pcf-pipelines/upgrade-buildpacks/pipeline.yml

  - task: update-upgrade-opsman-aws
    file: pcf-pipelines/ci/tasks/update_upgrade_opsman_aws.yml
    params:
      PIPELINE_PATH: release/pcf-pipelines/upgrade-ops-manager/aws/pipeline.yml
      ATC_EXTERNAL_URL: {{atc_external_url}}
      ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
      ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
      ATC_TEAM_NAME: {{atc_team_name}}
      AWS_SECRET_ACCESS_KEY: {{upgrade_opsman_aws_aws_secret_access_key}}
      AWS_REGION: {{upgrade_opsman_aws_aws_region}}
      AWS_VPC_ID: {{upgrade_opsman_aws_aws_vpc_id}}
      AWS_ACCESS_KEY_ID: {{upgrade_opsman_aws_aws_access_key_id}}
      EXISTING_OPSMAN_VM_NAME: {{upgrade_opsman_aws_existing_opsman_vm_name}}
      OPSMAN_URI: {{upgrade_opsman_aws_opsman_uri}}
      OPSMAN_ADMIN_USERNAME: {{upgrade_opsman_aws_opsman_admin_username}}
      OPSMAN_ADMIN_PASSWORD: {{upgrade_opsman_aws_opsman_admin_password}}
      OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}
      OPSMAN_MAJOR_MINOR_VERSION: {{opsman_major_minor_version}}
      PIVNET_TOKEN: {{pivnet_token}}
      GITHUB_TOKEN: {{github_token}}
      CHECK_NEW_OPSMAN_EVERY: 24h

- name: publish-release
  plan:
  - aggregate:
    - get: version
      passed: [update-pipelines]
      params: {bump: final}
    - get: pcf-pipelines
      passed: [update-pipelines]
    - get: cf-cli
    - get: om
      params:
        globs: [om-linux]

  - task: stamp-release-version
    file: pcf-pipelines/ci/tasks/stamp_release_version.yml

  - put: pcf-pipelines
    params:
      repository: pcf-pipelines-release
      tag: version/version
      tag_prefix: v

  - task: create-pivnet-metadata
    file: pcf-pipelines/ci/tasks/create_pivnet_metadata.yml
    params:
      AVAILABILITY: Selected User Groups Only

  - task: create-release
    file: pcf-pipelines/ci/tasks/create_release.yml
  - put: pivnet-release
    params:
      metadata_file: pivnet-metadata/metadata.yml
      file_glob: pcf-pipelines-release-files/*
      s3_filepath_prefix: {{pivnet_s3_filepath_prefix}}

  - put: version
    params:
      bump: major
      pre: rc

update_pipeline_params: &update_pipeline_params
  ATC_EXTERNAL_URL: {{atc_external_url}}
  ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
  ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
  ATC_TEAM_NAME: {{atc_team_name}}
  IAAS_TYPE: {{iaas_type}}
  PIVNET_TOKEN: {{pivnet_token}}
  PIVNET_POLL_INTERVAL: {{pivnet_poll_interval}}
  CF_API_URI: {{cf_api_uri}}
  CF_USER: {{cf_user}}
  CF_PASSWORD: {{cf_password}}
  CHECK_NEW_OPSMAN_EVERY: 24h
  OPSMAN_MAJOR_MINOR_VERSION: {{opsman_major_minor_version}}
  OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}
  OPSMAN_URI: {{opsman_uri}}
  OPSMAN_ADMIN_USERNAME: {{opsman_admin_username}}
  OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}
  GITHUB_TOKEN: {{github_token}}
