#!/bin/bash
set -eu

echo "$PEM" > pcf.pem
chmod 0600 pcf.pem

output_json=$(terraform output --json -state terraform-state/terraform.tfstate)

db_host=$(echo $output_json | jq --raw-output '.db_host.value')
db_username=$(echo $output_json | jq --raw-output '.db_username.value')
db_password=$(echo $output_json | jq --raw-output '.db_password.value')

cat > databases.sql <<EOF
CREATE DATABASE IF NOT EXISTS console;

CREATE DATABASE IF NOT EXISTS locket;
CREATE USER IF NOT EXISTS '$DB_LOCKET_USERNAME' IDENTIFIED BY '$DB_LOCKET_PASSWORD';
GRANT ALL ON locket.* TO '$DB_LOCKET_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS silk;
CREATE USER IF NOT EXISTS '$DB_SILK_USERNAME' IDENTIFIED BY '$DB_SILK_PASSWORD';
GRANT ALL ON silk.* TO '$DB_SILK_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS uaa;
CREATE USER IF NOT EXISTS '$DB_UAA_USERNAME' IDENTIFIED BY '$DB_UAA_PASSWORD';
GRANT ALL ON uaa.* TO '$DB_UAA_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS ccdb;
CREATE USER IF NOT EXISTS '$DB_CCDB_USERNAME' IDENTIFIED BY '$DB_CCDB_PASSWORD';
GRANT ALL ON ccdb.* TO '$DB_CCDB_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS notifications;
CREATE USER IF NOT EXISTS '$DB_NOTIFICATIONS_USERNAME' IDENTIFIED BY '$DB_NOTIFICATIONS_PASSWORD';
GRANT ALL ON notifications.* TO '$DB_NOTIFICATIONS_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS autoscale;
CREATE USER IF NOT EXISTS '$DB_AUTOSCALE_USERNAME' IDENTIFIED BY '$DB_AUTOSCALE_PASSWORD';
GRANT ALL ON autoscale.* TO '$DB_AUTOSCALE_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS app_usage_service;
CREATE USER IF NOT EXISTS '$DB_APP_USAGE_SERVICE_USERNAME' IDENTIFIED BY '$DB_APP_USAGE_SERVICE_PASSWORD';
GRANT ALL ON app_usage_service.* TO '$DB_APP_USAGE_SERVICE_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS routing;
CREATE USER IF NOT EXISTS '$DB_ROUTING_USERNAME' IDENTIFIED BY '$DB_ROUTING_PASSWORD';
GRANT ALL ON routing.* TO '$DB_ROUTING_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS diego;
CREATE USER IF NOT EXISTS '$DB_DIEGO_USERNAME' IDENTIFIED BY '$DB_DIEGO_PASSWORD';
GRANT ALL ON diego.* TO '$DB_DIEGO_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS account;
CREATE USER IF NOT EXISTS '$DB_ACCOUNTDB_USERNAME' IDENTIFIED BY '$DB_ACCOUNTDB_PASSWORD';
GRANT ALL ON account.* TO '$DB_ACCOUNTDB_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS nfsvolume;
CREATE USER IF NOT EXISTS '$DB_NFSVOLUMEDB_USERNAME' IDENTIFIED BY '$DB_NFSVOLUMEDB_PASSWORD';
GRANT ALL ON nfsvolume.* TO '$DB_NFSVOLUMEDB_USERNAME'@'%';

CREATE DATABASE IF NOT EXISTS networkpolicyserver;
CREATE USER IF NOT EXISTS '$DB_NETWORKPOLICYSERVERDB_USERNAME' IDENTIFIED BY '$DB_NETWORKPOLICYSERVERDB_PASSWORD';
GRANT ALL ON networkpolicyserver.* TO '$DB_NETWORKPOLICYSERVERDB_USERNAME'@'%';
EOF

scp -i pcf.pem -o StrictHostKeyChecking=no databases.sql "ubuntu@${OPSMAN_DOMAIN_OR_IP_ADDRESS}:/tmp/."
ssh -i pcf.pem -o StrictHostKeyChecking=no "ubuntu@${OPSMAN_DOMAIN_OR_IP_ADDRESS}" "mysql -h $db_host -u $db_username -p$db_password < /tmp/databases.sql"
